version: '2'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/endlessstudio/es-nginx:uwsgi-v2
    restart: always
    ports:
      - 8083:80/tcp
    environment:
      - TZ=Asia/Shanghai
      - UPSTREAM_UWSGI_SERVICES=server server01:4080;server server02:4080;
    mem_limit: 200m