version: '2'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/endlessstudio/es-nginx:http
    restart: always
    ports:
      - 8083:80/tcp
    environment:
      - TZ=Asia/Shanghai
      - UPSTREAM_SERVICES=server www.baidu.com;
    mem_limit: 200m