version: '2'
services:
  nginx:
    image: es-nginx:d-proxy
    # image: registry.cn-hangzhou.aliyuncs.com/endlessstudio/es-nginx:d-proxy
    restart: always
    ports:
      - 8083:80/tcp
    environment:
      - TZ=Asia/Shanghai
      - TARGET_HOST=appserver-v2.axinfu.com
      - TARGET_URL=http://appserver-v2.axinfu.com
    mem_limit: 209715200